- .github/workflows/verification_tests.yml
- src/scripts/create-project.ts
- add wait for storage to be ready for project
> add wait for storage to be ready for project

- integration/features/authAdmin.spec.ts
- integration/features/authentication.spec.ts
- integration/features/postgrest.spec.ts
- integration/features/realtime.spec.ts
- integration/features/storage.spec.ts
- src/auth/getUserToken.ts
- verification/spec/dashboard-api/sql.spec.ts
- add support for new sign-in screen
- add some logs
> add new sign-in screen support and some logs

- integration/features/postgrest.spec.ts
- update with postgrest now requires filter
> upd: update user test to have filters

- .github/workflows/sync_issues.yml
- gh-bugs-project/index.js
- gh-bugs-project/package-lock.json
- gh-bugs-project/package.json
- add gh issues sync scheduled job with bugs boards
> add gh issues sync scheduled job

- .github/workflows/integration_tests.yml
- .github/workflows/prod_verification_tests.yml
- .github/workflows/staging_verification_tests.yml
- .github/workflows/verification_tests.yml
- integration/.jest/teardown.ts
- integration/features/hooks.ts
- integration/features/storage.spec.ts
- integration/features/triggers.spec.ts
- integration/package-lock.json
- integration/package.json
- integration/supabase/migrations/20230104141145_data.sql
- integration/types/enums.ts
- package.json
- src/auth/getUserToken.ts
- src/common/helpers.ts
- src/common/retriedFetch.ts
- src/scripts/create-project.ts
- src/scripts/delete-project.ts
- src/scripts/restore-project.ts
- add step to pause and restore project
- run all tests again on the restored project
- increase stability of tests by reusing auth
- add triggers tests
> add restore project and triggers tests

- .github/workflows/prod_verification_tests.yml
- .github/workflows/staging_verification_tests.yml
- .github/workflows/verification_tests.yml
- .gitignore
- integration/features/triggers.spec.ts
- restore/.jest/jest-custom-reporter.ts
- restore/.jest/token.ts
- restore/features/data.spec.ts
- restore/features/hooks.ts
- restore/features/triggers.spec.ts
- restore/jest.config.ts
- restore/package-lock.json
- restore/package.json
- restore/preparations/data.ts
- restore/preparations/index.ts
- restore/preparations/prep.ts
- restore/preparations/triggers.ts
- restore/tsconfig.json
- move restoration tests to a separate folder
- add data restoration tests (auth, data, storage, procedure)
> move restoration tests to separate folder, add data tests

- gh-bugs-project/index.js
- update GitHub issues sync project with the new API (ProjectV2)
> update github bugs project sync with ProjectV2 API

- README.md
- update readme with project structure overview and links to test reports
> add some details to readme

- .github/workflows/integration_tests.yml
- .github/workflows/prod_verification_tests.yml
- .github/workflows/staging_verification_tests.yml
- .github/workflows/sync_issues.yml
- .github/workflows/verification_tests.yml
> add cache npm for local tests

- integration/features/storage.spec.ts
- src/scripts/delete-project.ts
- verification/spec/dashboard-api/api.spec.ts
- verification/spec/dashboard-gui/project.spec.ts
- verification/src/enums/feature.ts
- update api request that no longer returns project object
- update get bucket request that now returns extra fields
- update delete project script in case of jwt expiry
> fix a few things due to maintenance

- src/common/helpers.ts
- temp patch to avoid failures when pg got restarted after a project is reported to be healthy
> patch for pg restarts after project is healthy

- src/common/helpers.ts
- increase timeout after projects is active healthy
> fix increase timeout for previous patch

- .github/workflows/prod_verification_tests.yml
- currently prod only (update timeouts for integration tests)
> update timeouts for integration tests

- verification/spec/dashboard-gui/forms.spec.ts
- increase timeout for hubspot in forms tests
> increase timeout for hubspot

- verification/spec/dashboard-gui/forms.spec.ts
> update timeout in forms

- .github/workflows/prod_verification_tests.yml
- update cron to run prod tests each 8 hours
> more frequent prod tests

- .github/workflows/playwright.yml
- frontend/.gitignore
- frontend/package-lock.json
- frontend/package.json
- frontend/playwright.config.ts
- frontend/src/execution/persistent-ctx.ts
- frontend/src/execution/token-setup.ts
- frontend/tests/table-editor/nav.spec.ts
- frontend/tests/table-editor/view-controls.spec.ts
- package-lock.json
- package.json
> add frontend tests

- .github/workflows/playwright.yml
- fix: add api uri to fe workflow
> add api uri to fe workflow

- .github/workflows/playwright.yml
- add node_env env to fe workflow
> add node_env to fe workflow

- frontend/playwright.config.ts
> update timeout playwright.config.ts

- .github/workflows/playwright.yml
- fix fe report path in workflow
> fix fe report path in workflow

- README.md
- package.json
- src/auth/getUserToken.ts
- src/common/helpers.ts
- add few notes how to run locally
> add few notes how to run locally

- src/common/helpers.ts
- src/scripts/restore-project.ts
- verification/spec/dashboard-api/settings.spec.ts
- verification/spec/dashboard-gui/forms.spec.ts
- increase timeouts
- fix test to use new postgrest config url path
> increase timeouts; fix new pgrest config path

- .github/workflows/staging_verification_tests.yml
- .github/workflows/verification_tests.yml
- update staging timeout for integration tests
> update staging timeout for integration tests

- src/scripts/create-project.ts
- add errot log on create project
> add errot log on create project

- integration/package-lock.json
- integration/package.json
- package-lock.json
- package.json
- restore/package-lock.json
- restore/package.json
- verification/package-lock.json
- verification/package.json
> update eslint version

- integration/package-lock.json
- restore/package-lock.json
- verification/package-lock.json
> recreate lock files

- integration/features/authentication.spec.ts
- src/scripts/create-project.ts
- disable phone auth until gotrue fixes
> disable phone auth until gotrue fixes

- .github/workflows/prod_verification_tests.yml
> temp loosen alerts

- .github/workflows/staging_verification_tests.yml
- .github/workflows/verification_tests.yml
- integration/features/triggers.spec.ts
- src/scripts/restore-project.ts
- update staging org for tests
- enable staging slack alert
> update staging org for tests

- .github/workflows/prod_verification_tests.yml
- update prod_verification_tests.yml timeouts
> update prod_verification_tests.yml timeouts

- src/auth/getUserToken.ts
- src/common/timeoutFetch.ts
- src/scripts/create-project.ts
- verification/spec/dashboard-gui/project.spec.ts
- fix: create project test updates
> fix: create project test updates

- .github/workflows/prod_verification_tests.yml
- .github/workflows/staging_verification_tests.yml
- limit workflow concurrency for prod tests
- limit workflow concurrency for staging tests
> chore: limit workflow concurrency for prod tests

- .github/workflows/prod_fe_tests.yml
- .github/workflows/prod_verification_tests.yml
- .github/workflows/staging_verification_tests.yml
- frontend/tests/sql-editor/nav.spec.ts
- frontend/tests/table-editor/view-controls.spec.ts
- src/scripts/create-project.ts
- verification/spec/dashboard-gui/forms.spec.ts
- reenable support test; 
- add workflow for fe
> feat: reenable support test; add workflow for fe

- frontend/tests/sql-editor/nav.spec.ts
- frontend/tests/table-editor/view-controls.spec.ts
- fix: update filter view test
> fix: update filter view test

- integration/features/hooks.ts
> fix: change hook error

- .github/workflows/prod_fe_tests.yml
- .github/workflows/prod_verification_tests.yml
- .github/workflows/staging_verification_tests.yml
- .github/workflows/verification_tests.yml
- frontend/src/execution/token-setup.ts
- restore/.jest/token.ts
- src/auth/getUserToken.ts
- src/scripts/create-project.ts
- src/scripts/delete-project.ts
- src/scripts/restore-project.ts
- verification/.jest/token.ts
- feat: unified retries on auth
> feat: unified retries on auth

- verification/spec/dashboard-gui/forms.spec.ts
- fix: support form completed new screen
> fix: support completed form

- src/auth/getUserToken.ts
- src/common/helpers.ts
- src/scripts/create-project.ts
- src/scripts/create-project.v0.ts
- src/scripts/delete-project.ts
- src/scripts/delete-project.v0.ts
- src/scripts/restore-project.ts
- src/scripts/restore-project.v0.ts
- verification/spec/dashboard-api/api.spec.ts
- verification/spec/dashboard-api/home.spec.ts
- verification/spec/dashboard-api/hooks.ts
- verification/spec/dashboard-api/settings.spec.ts
- verification/spec/dashboard-api/sql.spec.ts
- verification/spec/dashboard-api/tables.spec.ts
- verification/spec/dashboard-api/users.spec.ts
- verification/spec/dashboard-gui/project.spec.ts
- fix: use retried fetched everywhere
> fix: use retried fetched everywhere

- src/scripts/create-project.ts
- src/scripts/create-project.v0.ts
> fix: remove kps_enabled

- verification/spec/dashboard-api/forms.spec.ts
- verification/spec/dashboard-gui/forms.spec.ts
- verification/src/types/hubspot.ts
- feat: add feedback tests to stable suite
> feat: add feedback tests to stable suite

- .github/workflows/prod_verification_tests.yml
- src/common/helpers.ts
- src/scripts/create-project.v0.ts
- src/scripts/restore-project.v0.ts
- chore: increase timeout cause restores are too slow, pause project can take tens of minutes
- increase api calls timeouts, cause api can sometime take too long to respond
> chore: increase timeout cause restores is too slow

- .github/workflows/sync_issues.yml
- gh-bugs-project/index.js
- gh-bugs-project/package-lock.json
- gh-bugs-project/package.json
- package-lock.json
- package.json
> fix: update octokit dep

- .github/workflows/staging_verification_tests.yml
- .github/workflows/verification_tests.yml
- integration/features/hooks.ts
- restore/features/hooks.ts
- restore/features/triggers.spec.ts
- restore/preparations/prep.ts
> chore: update staging org id

- src/scripts/apply-migrations.ts
- src/scripts/create-project.ts
- src/scripts/create-project.v0.ts
- verification/spec/dashboard-gui/forms.spec.ts
> feat: connect through pooler

- restore/features/hooks.ts
- restore/features/triggers.spec.ts
- src/common/retriedFetch.ts
- src/common/timeout.ts
- src/common/timeoutFetch.ts
> fix: add abort controller

- src/common/timeout.ts
- src/common/timeoutFetch.ts
Bug fix, feature, docs update, ...
Please link any relevant issues here.
Feel free to include screenshots if it includes visual changes.
Add any other context or screenshots.
> Egor romanov patch 1

- integration/jest.config.ts
- src/common/retriedFetch.ts
> increase timeouts

- .github/workflows/prod_verification_tests.yml
chore: update prod org id for integration tests
> chore: update prod org id for integration tests

- integration/features/authentication.spec.ts
> chore: update user metadata
